- name: 'install python'
  apt:
    name: python3
    state: latest
    update_cache: true
- name: 'install pip'
  apt:
    name: python3-pip
    state: latest
    update_cache: true

- name: 'update apt and install preliminary packages'
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: latest
    update_cache: true

- name: 'add GPG key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable"
    state: present

- name: 'latest version of Docker Engine and containerd'
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true